openapi: 3.0.0
servers:
  - url: 'http://petstore.example.com/api'
info:
  description: >-
    Rust Edge Gateway Pet Store Demo - demonstrates the same API working with
    multiple storage backends (SQLite, PostgreSQL, MySQL, MinIO, FTP)
  version: 1.0.0
  title: Rust Edge Gateway Pet Store
  license:
    name: MIT
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
paths:
  /pets:
    get:
      tags:
        - pet
      summary: List all pets
      operationId: listPets
      parameters:
        - name: status
          in: query
          description: Filter by status
          schema:
            type: string
            enum: [available, pending, sold]
        - name: limit
          in: query
          description: Maximum number of pets to return
          schema:
            type: integer
            default: 100
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      tags:
        - pet
      summary: Create a new pet
      operationId: createPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePet'
      responses:
        '201':
          description: Pet created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid input
  /pets/{petId}:
    get:
      tags:
        - pet
      summary: Get a pet by ID
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pet found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
    put:
      tags:
        - pet
      summary: Update a pet
      operationId: updatePet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePet'
      responses:
        '200':
          description: Pet updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
    delete:
      tags:
        - pet
      summary: Delete a pet
      operationId: deletePet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Pet deleted
        '404':
          description: Pet not found
components:
  schemas:
    Pet:
      type: object
      required: [id, name, status]
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [available, pending, sold]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    CreatePet:
      type: object
      required: [name]
      properties:
        name:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [available, pending, sold]
          default: available
    UpdatePet:
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [available, pending, sold]

